SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Lodestar].[LSSERVICEPOINT](
	[UIDSERVICEPOINT] [numeric](19, 0) NULL,
	[UIDMARKET] [numeric](19, 0) NULL,
	[SERVICEPOINTID] [varchar](64) NULL,
	[SERVICEPOINTNAME] [varchar](64) NULL,
	[UIDPREMISE] [numeric](19, 0) NULL,
	[LSUSER] [varchar](64) NULL,
	[LSTIME] [date] NULL,
	[GROSSSQFOOTAGE] [float] NULL,
	[UIDADDRESS] [numeric](19, 0) NULL
) ON [PRIMARY]
GO
