SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Staging].[LS_METER_HISTORY](
	[UIDMETER] [int] NOT NULL,
	[STARTTIME] [datetime2](7) NULL,
	[STOPTIME] [datetime2](7) NULL,
	[SERVICETYPECODE] [varchar](64) NULL
) ON [PRIMARY]
GO
