SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Lodestar].[SVCPROVIDER](
	[UIDSVCPROVIDER] [numeric](19, 0) NULL,
	[SVCPROVIDERCODE] [varchar](32) NULL,
	[SVCPROVIDERNAME] [varchar](64) NULL,
	[LSUSER] [varchar](64) NULL,
	[LSTIME] [date] NULL
) ON [PRIMARY]
GO
