SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Lodestar].[BILLDETERMINANT](
	[UIDBILLDETERMINANT] [numeric](5, 0) NULL,
	[BILLDETERMCODE] [varchar](64) NULL,
	[IDENTIFIER] [varchar](32) NULL,
	[BILLDETERMNAME] [varchar](64) NULL,
	[UOMCODE] [varchar](64) NULL,
	[BILLHISTCOLNAME] [varchar](32) NULL,
	[AGGREGATE] [char](1) NULL,
	[BILLDETERMTYPECODE] [varchar](64) NULL,
	[LSUSER] [varchar](64) NULL,
	[LSTIME] [date] NULL
) ON [PRIMARY]
GO
