SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Lodestar].[BILLHISTORYVALUE](
	[UIDBILLHISTORY] [numeric](19, 0) NULL,
	[UIDBILLDETERMINANT] [numeric](5, 0) NULL,
	[VAL] [float] NULL,
	[LSUSER] [varchar](64) NULL,
	[LSTIME] [date] NULL,
	[REPORTED] [char](1) NULL,
	[REPORTDATE] [date] NULL
) ON [PRIMARY]
GO
