SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Lodestar].[ACCTDIRECTORY](
	[UIDACCOUNT] [numeric](19, 0) NULL,
	[UIDDIRECTORY] [numeric](19, 0) NULL,
	[FAXFLAG] [char](1) NULL,
	[CONTACTTYPE] [varchar](64) NULL,
	[LSUSER] [varchar](64) NULL,
	[LSTIME] [date] NULL
) ON [PRIMARY]
GO
