SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Staging].[MM_CURRENT_ROUTE_READINGS](
	[ID] [int] NOT NULL,
	[NEW_READING] [float] NOT NULL,
	[NEW_READ_DATE] [datetime2](7) NULL
) ON [PRIMARY]
GO
