SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Staging].[MM_METER_INFO](
	[METER_ID] [nvarchar](50) NOT NULL,
	[METER_SN] [nvarchar](30) NOT NULL,
	[LOCATION_ID] [nvarchar](30) NOT NULL,
	[STATUS_CODE] [nchar](2) NOT NULL,
	[MONTHLY_READING_TYPE] [nvarchar](30) NULL
) ON [PRIMARY]
GO
