SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Lodestar].[RECEIVABLETYPE](
	[UIDRECEIVABLETYPE] [numeric](19, 0) NULL,
	[RECEIVABLETYPECODE] [varchar](64) NULL,
	[DESCRIPTION] [varchar](254) NULL,
	[LSUSER] [varchar](64) NULL,
	[LSTIME] [date] NULL
) ON [PRIMARY]
GO
