SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Staging].[SPOTS_HQ_QUANTITY](
	[BL_ID] [varchar](8) NOT NULL,
	[NAME] [varchar](75) NULL,
	[AREA_GROS_BESTEST] [float] NULL,
	[UNC_LAND_ENT_CLASS_ID] [varchar](1) NULL
) ON [PRIMARY]
GO
