SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Lodestar].[FRSDEPT](
	[UIDFRSDEPT] [numeric](19, 0) NULL,
	[FRSDEPTNUM] [varchar](32) NULL,
	[FRSDEPTNAME] [varchar](64) NULL,
	[LSUSER] [varchar](64) NULL,
	[LSTIME] [date] NULL
) ON [PRIMARY]
GO
