SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Lodestar].[ACCOUNTCLASS](
	[UIDACCOUNTCLASS] [numeric](19, 0) NULL,
	[ACCOUNTCLASSCODE] [varchar](64) NULL,
	[ACCOUNTCLASSNAME] [varchar](64) NULL,
	[LSUSER] [varchar](64) NULL,
	[LSTIME] [date] NULL
) ON [PRIMARY]
GO
