SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Staging].[MM_METER_READING_PROPERTIES](
	[METER_ID] [nvarchar](50) NOT NULL,
	[MREAD_PROP_NAME] [nvarchar](32) NOT NULL,
	[MREAD_PROP_VALUE] [nvarchar](128) NULL
) ON [PRIMARY]
GO
