SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Lodestar].[FUNDINGTYPE](
	[UIDFUNDINGTYPE] [numeric](19, 0) NULL,
	[FUNDINGTYPECODE] [varchar](32) NULL,
	[FUNDINGTYPENAME] [varchar](64) NULL,
	[LSUSER] [varchar](64) NULL,
	[LSTIME] [date] NULL
) ON [PRIMARY]
GO
