SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Lodestar].[SERVICETYPE](
	[SERVICETYPECODE] [varchar](64) NULL,
	[SERVICETYPENAME] [varchar](64) NULL,
	[DESCRIPTION] [varchar](254) NULL,
	[LSUSER] [varchar](64) NULL,
	[LSTIME] [date] NULL
) ON [PRIMARY]
GO
