SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Lodestar].[BILLINGCYCLEDATE](
	[UIDBILLINGCYCLE] [numeric](19, 0) NULL,
	[READDATE] [date] NULL,
	[BILLMONTH] [numeric](5, 0) NULL,
	[LSUSER] [varchar](64) NULL,
	[LSTIME] [date] NULL
) ON [PRIMARY]
GO
