SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Lodestar].[LSMARKET](
	[UIDMARKET] [numeric](19, 0) NULL,
	[MARKETID] [varchar](64) NULL,
	[SERVICETYPE] [varchar](64) NULL,
	[LSUSER] [varchar](64) NULL,
	[LSTIME] [date] NULL
) ON [PRIMARY]
GO
