SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Lodestar].[VALSTATUS](
	[UIDVALSTATUS] [numeric](19, 0) NULL,
	[VALSTATUSCODE] [varchar](32) NULL,
	[VALSTATUSNAME] [varchar](64) NULL,
	[LSUSER] [varchar](64) NULL,
	[LSTIME] [date] NULL
) ON [PRIMARY]
GO
