SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Lodestar].[RDINPUT](
	[RDINPUTNUM] [numeric](19, 0) NULL,
	[BFEXPSTEAM] [float] NULL,
	[BFEXPELEC] [float] NULL,
	[BVEXPSTEAM] [float] NULL,
	[NBFEXPELEC] [float] NULL,
	[DRCSTEAM] [float] NULL,
	[DRCELEC] [float] NULL,
	[MARGINALSTEAMRATE] [float] NULL,
	[INCNONCHILLSTEAM] [float] NULL,
	[INCCHILLSTEAM] [float] NULL,
	[INCELEC] [float] NULL,
	[RATEDIFFELEC] [float] NULL,
	[SYSLEVELSTEAMUSAGE] [float] NULL,
	[SUMMERDEMANDCOST] [float] NULL,
	[WINTERDEMANDCOST] [float] NULL,
	[LSUSER] [varchar](64) NULL,
	[LSTIME] [date] NULL,
	[INCSTEAMDEMAND] [float] NULL,
	[TIERONEPCT] [float] NULL,
	[TIERTWOPCT] [float] NULL,
	[TOTELECUSAGE] [float] NULL,
	[INCDELECDEMAND] [float] NULL,
	[BFEXPCW] [float] NULL,
	[BVEXPCW] [float] NULL,
	[DRCCW] [float] NULL,
	[INCCW] [float] NULL
) ON [PRIMARY]
GO
