SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Lodestar].[LSSRVCPTACCT](
	[UIDSERVICEPOINT] [numeric](19, 0) NULL,
	[UIDACCOUNT] [numeric](19, 0) NULL,
	[STARTTIME] [date] NULL,
	[STOPTIME] [date] NULL,
	[LSUSER] [varchar](64) NULL,
	[LSTIME] [date] NULL
) ON [PRIMARY]
GO
