SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Lodestar].[METERREAD](
	[UIDMETER] [numeric](19, 0) NULL,
	[METERREADTIME] [date] NULL,
	[UIDBILLDETERMINANT] [numeric](19, 0) NULL,
	[STOPREADTIME] [date] NULL,
	[STOPREADING] [float] NULL,
	[STARTREADTIME] [date] NULL,
	[STARTREADING] [float] NULL,
	[PEAKTIME] [date] NULL,
	[PEAKVALUE] [float] NULL,
	[METERREADMONTH] [numeric](5, 0) NULL,
	[THERMFACTOR] [float] NULL,
	[LSUSER] [varchar](64) NULL,
	[LSTIME] [date] NULL,
	[CONSUMPTION] [float] NULL,
	[UIDVALSTATUS] [numeric](19, 0) NULL,
	[UIDREADTYPE] [numeric](19, 0) NULL
) ON [PRIMARY]
GO
