SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Lodestar].[READTYPE](
	[UIDREADTYPE] [numeric](19, 0) NULL,
	[READTYPECODE] [varchar](32) NULL,
	[READTYPENAME] [varchar](64) NULL,
	[LSUSER] [varchar](64) NULL,
	[LSTIME] [date] NULL
) ON [PRIMARY]
GO
